[build][test] Fixed Netty dependencies and TestRead::testRead
Netty dependencies clashed between fat jar and specific modules,
leading to NoSuchMethodErrors. Fixed via build exclusions.

Disabled the marking of JMH sources in IntelliJ as it has issues.

Re-enabled TestRead::testRead and added a try-with-resources to
it. Also added a TODO about a potentieal issue in HttpClient5.