Upgrade Kafka Client dependency
After talking to Kafka team upgrading the Kafka dependency
0.8.2.42 as 0.8.2.20 has known issues.

This requires the Kafka Server to be 0.9 as well, otherwise
it fails with following cryptic message.

https://issues.apache.org/jira/browse/KAFKA-2750

[2015-11-04 18:55:43,583] ERROR Uncaught error in kafka producer I/O
thread: (org.apache.kafka.clients.producer.internals.Sender)
org.apache.kafka.common.protocol.types.SchemaException: Error reading
field 'throttle_time_ms': java.nio.BufferUnderflowException