[router] Possible fix of router stop stuck issue.
Recently, Venice SRE experienced a lot of router stuck issue during
deployment, and here are the related logs:
2018/08/21 17:55:10.939 INFO [D2ServerManager] [Thread-1]
[venice-router-war] [] d2 server deannounced
2018/08/21 17:55:10.939 INFO [ClientCnxn]
[ForkJoinPool.commonPool-worker-2-EventThread] [venice-router-war] []
EventThread shut down for session: 0x16500ba96829744
2018/08/21 17:55:40.839 INFO [ResourceRegistry]
[ResourceRegistryGlobalShutdown] [venice-router-war] [] Shutting down
remaining ResourceRegistries
2018/08/21 17:55:40.840 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-1]
[venice-router-war] [] [1] Starting shutdown
2018/08/21 17:55:40.840 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-2]
[venice-router-war] [] [2] Starting shutdown
2018/08/21 17:55:40.842 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-3]
[venice-router-war] [] [3] Starting shutdown
2018/08/21 17:55:40.851 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-1]
[venice-router-war] [] [1] Starting phase 2
2018/08/21 17:55:40.851 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-1]
[venice-router-war] [] [1] Starting shutdown:
com.linkedin.ddsstorage.netty4.misc.ShutdownableHashedWheelTimer@224e6e88
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-1]
[venice-router-war] [] [1] Starting shutdown:
com.linkedin.ddsstorage.netty4.misc.ShutdownableNioEventLoopGroup@4fa5cc73
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-3]
[venice-router-war] [] [3] Starting phase 2
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-2]
[venice-router-war] [] [2] Starting phase 2
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-3]
[venice-router-war] [] [3] Starting shutdown:
com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@5a8fd55c
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-2]
[venice-router-war] [] [2] Starting shutdown:
com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@44518b1a
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-1]
[venice-router-war] [] [1] Starting shutdown:
com.linkedin.ddsstorage.netty4.misc.ShutdownableNioEventLoopGroup@66b6873f
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-3]
[venice-router-war] [] [3] Waiting for shutdown:
com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@5a8fd55c
2018/08/21 17:55:40.854 INFO [ResourceRegistry]
[com.linkedin.ddsstorage.base.registry.ResourceRegistry-shutdown-2]
[venice-router-war] [] [2] Waiting for shutdown:
com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@44518b1a
2018/08/21 17:55:40.854 INFO [Router]
[shutdown-com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@5a8fd55c]
[venice-router-war] [] Closing server channel: [id: 0xa979eb12,
L:/0:0:0:0:0:0:0:0:2921]
2018/08/21 17:55:40.854 INFO [Router]
[shutdown-com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@44518b1a]
[venice-router-war] [] Closing server channel: [id: 0x9a362fc4,
L:/0:0:0:0:0:0:0:0:1689]
2018/08/21 17:55:40.855 ERROR [rejectedExecution]
[shutdown-com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@5a8fd55c]
[venice-router-war] [] Failed to submit a listener notification task.
Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor
terminated

From the logs, it seems {@link
ResourceRegistry.State#performShutdown()} is not shutting down
resources synchronously when necessary, which could cause some
race condition.
For example, "executor" initialized in {@link #startInner()}
could be shutdown earlier than
{@link #router} and {@link #secureRouter}, then the shutdown of
{@link #router} and {@link #secureRouter}
would be blocked because of the following exception:
2018/08/21 17:55:40.855 ERROR [rejectedExecution]
[shutdown-com.linkedin.ddsstorage.router.impl.netty4.Router4Impl$$Lambda$230/594142688@5a8fd55c]
[venice-router-war] [] Failed to submit a listener notification
task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor
terminated

The new introduced shutdown logic is trying to shutdown resources in
order.

{@link Router4Impl#shutdown()} will trigger the shutdown thread,
so here will trigger shutdown thread of {@link #router}
and {@link #secureRouter} together, and wait for them to complete
after.

TODO: figure out the root cause why {@link
ResourceRegistry.State#performShutdown()} is not executing shutdown
logic
correctly.

RB=1400582
BUG=VOLDENG-4214
G=voldemort-reviewers
R=acurtis,mwise,chgao,sdwu,yayan,solu
A=sdwu,acurtis