[samza] Avoid creating optional inside VeniceSystemFactory. (#2209)
Problem Statement
In downstream dependencies, VeniceSystemFactory encounters issues serializing Optional fields
that were recently added. During the Apache Beam runner job initialization phase, it needs to
serialize the VeniceSystemFactory object. Since Java does not support serializing Optional fields
(added in a previous change: #2041), this causes the job to fail with the following exception:
java.io.NotSerializableException: java.util.Optional.

Solution
We added a new API to allow passing specific D2 clients instead of using the previous protected
Optional fields for D2 clients.
```
public SystemProducer getProducer(
    String systemName,
    String storeName,
    boolean veniceAggregate,
    String pushTypeString,
    Config config,
    Optional<D2Client> providedChildColoD2Client,
    Optional<D2Client> providedPrimaryControllerColoD2Client)
```