[router] Fixed a router netty buffer leaking issue
This code change addressed two issues essentially:
1. The netty byte buffer double free issue when using streaming.
Error stack:
WARN [ReferenceCountUtil] [RouterThread-2-3] [venice-router-war] [] Failed to release a message:
SuccessfulStreamingResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(freed))
HTTP/1.1 200 OK
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
This issue was triggered when Router fails to send the response to the Client and both {@link VeniceChunkedResponse} and {@link AsyncFullHttpRequestHandler}
will try to release the dummy successful response, which is benign, but will cause massive logging.
The fix is to only free the {@link SuccessfulStreamingResponse} in {@link AsyncFullHttpRequestHandler} in failure scenarios.

2. The netty byte buffer leaking issue is triggered by long-tail retry.
DDS lib only expects {@link RouterException} for {@link ScatterGatherMode} implementations, but {@link VeniceDelegateMode} would throw
{@link VeniceException} in some scenarios, and these unexpected exceptions will cause {@link ScatterGatherRequestHandlerImpl#prepareRetry}
to bypass the release of the http request object.
The fix is trying to throw {@link RouterException} all the time in {@link VeniceDelegateMode}, and long-term fix should be to improve
the resilience of this function: {@link ScatterGatherMode#scatter} in DDS lib.

RB=2240779
BUG=VENG-6405
R=anaberez,fvillega,shuhliu,zpolicze,xnma,nithakka,yurzhou,sdwu,zfan,mnhuang,xyin,smaji,jlliu
A=smaji