[common][h2v][samza][server] Improved VeniceWriter debugging and resiliency
Default config change:
- The ApacheKafkaProducer's "retries" config is bumped from 2 to infinity
  in order to be capable of riding over transient Kafka broker leadership
  changes manifesting in NotLeaderForPartitionException. The lack of
  leader should usually last just a few seconds, but can last several
  minutes in some cases. This config is still overridable, as before.

Main code change:
- The VeniceWriter now populates the control messages' debugInfo map with
  the use of a new utility function at Utils#getDebugInfo(). The map
  contains the following entries relative to the current process:
  - host
  - path (current working directory)
  - pid
  - version (of the venice-common jar found in the classpath)
  - user
- The server's StoreIngestionTask does the necessary bookkeeping to store
  the debugInfo when a segment is started, and prints that info when a DIV
  error occurs. The new DIV error logging looks like this:

com.linkedin.venice.exceptions.validation.MissingDataException: MISSING data detected for producer GUID: 6e8c7631430b451781622bb95b808d68,
message type: CONTROL_MESSAGE (END_OF_PUSH),
partition: 2,
previous segment: 0,
incoming segment: 0,
previous sequence number: 2,
incoming sequence number: 4,
aggregates: {},
debugInfo: {
	path: /current/working/dir/of/java/process
	host: lsg1-app1234.prod.linkedin.com
	pid: 60982
	version: 0.2.64
	user: xyz
}

Test:
- Added a new test case at UtilsTest#testGetDebugInfo()

RB=1737428
BUG=VOLDENG-4855
G=voldemort-reviewers
R=mnhuang,xyin,anaberez,sdwu,goliu,smaji
A=mnhuang