[server] Capture exception while resetting ERROR replica (#1928)
We mark replicas to ERROR state if servers hit some ingestion ERROR. But if the participant server hosts already has. 
a helix state transition or other messages pending, it will throw the following helix exception causing the SIT to. 
bubble up the exception.  

org.apache.helix.HelixException: Can't SET_TO_ERROR state for resource because a pending messages.   
This PR captures and asborbs such exceptions.